Skipping results e2e as it's failing due to PSA
due to PSA in pipelines, results deployment is failing
but adding restriced fields also doesn't work
```
Error: container has runAsNonRoot and image will run as root
(pod: "tekton-results-postgres-0_tekton-pipelines(a7492fa3-e313-4fb7-ae69-9b0a4e14d557)", container: postgres)
```
so need to check in results.

Signed-off-by: Shivam Mukhade <smukhade@redhat.com>